version: '3.5'
services:

  proxy:
    extra_hosts:
      - "archive.ubuntu.com:185.125.190.36"
    # image: cefore/base
    build: ./proxy
    container_name: "proxy"
    working_dir: "/proxy"
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./Torrent_Proxy/:/proxy/torrent_proxy
      - ./evaluation/:/proxy/evaluation/
    networks:
      ip_net:
        ipv4_address: 10.0.1.102 # 10.0.1.102
      ccn_net:
        ipv4_address: 10.0.2.102 # 10.0.1.102

  client:
    extra_hosts:
      - "archive.ubuntu.com:185.125.190.36"
    # image: cefore/base
    build: ./client
    container_name: "client"
    working_dir: "/client"
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./ccn_torrent_client/:/client/ccn_torrent_client
      - ./evaluation/:/client/evaluation/
    networks:
      ccn_net:
        ipv4_address: 10.0.2.202 # 10.0.1.102

  producer:
    extra_hosts:
      - "archive.ubuntu.com:185.125.190.36"
    # image: queeno/ubuntu-desktop
    build: ./producer
    container_name: "producer"
    hostname: "producer"
    working_dir: "/producer"
    tty: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./evaluation/:/producer/evaluation
    ports:
      - "0.0.0.0:59001:5901"
    networks:
      ip_net:
        ipv4_address: 10.0.1.203


networks:
  ip_net:
    name: ip_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

  ccn_net:
    name: ccn_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
